---
name: laravel-boost
description: Use when editing AGENTS.md, CLAUDE.md, agent instructions, AI guidelines, project memory, learned preferences, or Boost-managed skills; explains where to put changes and when to run boost:update
---

# Laravel Boost

Laravel Boost installs and maintains AI context for this project. Use this skill before editing generated agent instruction files or when the user asks you to change agent guidelines, remember a preference, learn project conventions, update instructions, or modify AI-facing behavior.

## When To Use This Skill

- The user asks to edit or update `AGENTS.md`, `CLAUDE.md`, or another agent instruction file.
- The user asks you to remember, learn, or store a project convention.
- The user asks you to change guidelines, AI instructions, coding rules, agent behavior, or project preferences.
- You are about to modify Boost-managed guidelines or skills.

## Where Project Instructions Live

- Project-specific AI instructions belong in `.ai/guidelines`.
- Add or update custom guidance there instead of editing generated agent files directly.
- Keep instructions focused and actionable so Boost can compose them into each supported agent's format.

## Do Not Edit Generated Agent Files

- Never edit `AGENTS.md` to change project guidelines.
- Never edit `CLAUDE.md` to change project guidelines.
- `AGENTS.md` is generated by Boost for agents that use that file.
- `CLAUDE.md` is generated by Boost for Claude Code when that agent is configured.
- Manual changes to generated files may be overwritten the next time Boost syncs guidelines or skills.

## Syncing Boost Changes

- After changing Boost-managed guidelines or skills, run `{{ $assist->artisanCommand('boost:update') }}`.
- Use `{{ $assist->artisanCommand('boost:update --discover') }}` when newly installed packages may provide additional guidelines or skills.
- Do not skip the update step after adding or changing `.ai/guidelines` content, because agents consume the synced outputs.
